### PR TITLE
Use BOM station list data

### PR DESCRIPTION
**Pull request by adamhsparks**
use httr::http_response to check JSON urls in `get_current_weather()`

fix tests for `get_ag_bulletin()`

### CODE REVIEW

**Comment by HughParsonage** [comment]
1. I think updating the metadata during every call is unnecessary. You should cache them as an internal data frame, `devtools::use_data(JSONurl_latlon_by_station_name, internal = TRUE)` calling the metadata if necessary or if the user requests it (via an argument).

**Comment by adamhsparks** [comment]
Updated with a database of JSON URLs and a database of station locations.

**Comment by adamhsparks** [comment]
I've written better tests written for the internal database update functions, cleaned up the `data-raw` folder and upgraded to v0.0.3.

I think it's ready for your review and comment again, @HughParsonage.

**Comment by adamhsparks** [comment]
No complaints here. Agree. We can do that and just omit them completely as I already have with any that are NA on package creation.

**Comment by adamhsparks** [comment]
Thanks @HughParsonage for the good feedback.

**Pull request merged**
